version: "3.8"


services:
  www:
    container_name: thiago-php
    build: ./
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/html
      
    links:
      - db

  db:
    
    image: mysql:latest
    container_name: thiago-db
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
   
  phpmyadmin:
    container_name: thiago-phpadmin
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 